### ISSUE TITLE
How to load and include WebAssembly ?

### ISSUE THREAD

**Issue by sandrobilbeisi** [davidedc/Fizzygum#164]
How to load and include WebAssembly ?

should we load that from JavaScript source ?

I am working on an STL 3D file viewer and want to make that available as a Fizzygum widget.

**Comment by davidedc** [comment]
Ciao Sandro,

very cool!

I think that if you serve fizzygum via a web server then you should be able to just do everything "normally". If you serve via the file:// protocol then there might be permission issues, in which case yes you might have to load from JavaScript source, maybe then put it an ArrayBuffer and consume it via that.

I'll have to do something like that when loading sounds to play via WebAudio API: file:// won't allow sound files to be loaded and played normally as they would if served via a server.

see also https://github.com/webpack/webpack/issues/7918

Also note that "fetch" has similar issues, it won't work via file:// the same it works via network. https://github.com/WebAssembly/design/issues/1200 .

Hope this is what you asked, closing for now.
